<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_5</name>
   <tag></tag>
   <elementGuidId>305ed6c4-383d-4513-9f22-c8dd2be49f68</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.new.day:nth-child(7)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' new ') and contains(concat(' ', normalize-space(@class), ' '), ' day ') and (position() = 7)]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;5&quot;s] >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>df86b9d3-8f57-4ee9-9f9c-4d153c34ce71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>new day</value>
      <webElementGuid>a162f001-a10e-48bf-a3e0-3361b18c5f78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>5d4da0bb-70ad-4e9c-ab37-508c1673463b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>@text</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>69ffff22-5e94-4a9d-a3ec-7cb7463b0a30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-65e003d2227f133a97caf5dae710455a</value>
      <webElementGuid>6ef6483f-423f-4d51-9b25-ad8324c2ae36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' new ') and contains(concat(' ', normalize-space(@class), ' '), ' day ') and (position() = 7)]</value>
      <webElementGuid>c40267cc-1467-464d-ac2f-eb16ff6a6f28</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' new ') and contains(concat(' ', normalize-space(@class), ' '), ' day ') and (position() = 7)]</value>
      <webElementGuid>7e651445-b078-421d-a493-56728a08e3db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '5' or . = '5')]</value>
      <webElementGuid>33d1353f-5729-4ef3-9af0-309ced67e278</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
