<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>a11156a9-6096-4817-814b-593532fbe021</elementGuidId>
    <imagePath></imagePath>
    <name>link_viewProductDetails</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/app-root[1]/div[1]/app-detail[1]/div[2]/div[1]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'product/${product_id}') and equals(@text,'Claw Hammer with Shock Reduction Grip
            More information')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>a &gt;&gt; internal:has-text="${link_viewProductDetails_internalHasText}"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Claw Hammer with Shock Reduction Grip
        More information</value>
        <webElementGuid>3601c10e-8ce5-48a6-b377-26ef43f90685</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>product/${{product_id}}</value>
        <webElementGuid>3601c10e-8ce5-48a6-b377-26ef43f90685</webElementGuid>
    </webElementProperties>
</WebElementEntity>